### ISSUE TITLE
scale should probably be 1 in absence of metadata

### ISSUE THREAD

**Issue by tlambert03** [BodenmillerGroup/napari-czifile2#3]
howdie and thanks for napari-czifile

I just needed to use CZI files in napari so installed it and ran into an issue where the reader was returning `0` for one axis in the `scale` parameter... (i think it was `f.scale_z_um`) here:

https://github.com/BodenmillerGroup/napari-czifile2/blob/e92d2e38db0735935d5bcdf307f422d19cc6aea3/napari_czifile2/_reader.py#L32

this eventually causes napari to fail when calculating transforms (which we should certainly also handle on our side), but just thought I'd mention it here.  probable best to set the value to `1` in the absence of metadata?

**Comment by jwindhager** [comment]
Hi Talley,

thanks a lot for giving napari-czifile a try an reporting this issue!

I'm a bit puzzled by this, though, as

https://github.com/BodenmillerGroup/napari-czifile2/blob/e92d2e38db0735935d5bcdf307f422d19cc6aea3/napari_czifile2/io.py#L47-L48

and 

https://github.com/BodenmillerGroup/napari-czifile2/blob/e92d2e38db0735935d5bcdf307f422d19cc6aea3/napari_czifile2/io.py#L104-L108

Therefore, the only reason I can see for `f.scale_z_um` to be `0` is if it is actually set to `0` in the (present) file metadata. Could you maybe verify this? In any case, I should probably fix this to default to `1` for invalid metadata, as you suggested. Will release a fix asap. Thanks again for reporting this!

**Comment by tlambert03** [comment]
Cool; thanks.  Yeah it’s totally possible it’s in the metadata itself ... and again, it does seem like something that napari should fix too! Thanks!

**Comment by tlambert03** [comment]
yep, just checked and you were correct, it's set to 0 in the metadata.  It was incorrect to call it the "absence" of metadata.  (It's not a z-stack for what it's worth ... ).  I see you also noticed https://github.com/napari/napari/issues/2569, which is probably the "real" fix for this ... but thank you for https://github.com/BodenmillerGroup/napari-czifile2/commit/2594c49b0f739f00dc74cf4fbd48f133cb6a3d95!

**Comment by jwindhager** [comment]
Thanks for letting me know! Was doubting myself already :sweat_smile:

Please do let me know if anything else pops up!
